config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  devise_scope :user do
    get 'profile', to: 'users/registrations#show'
  end
  resources :albums

  get '*unmatched_route', to: 'application#render_404' unless Rails.env.development?

  mount RailsTask::API => '/'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user

  paginates_per 10

  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates_uniqueness_of :name
  validates_length_of :name, maximum: 20
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, PhotoUploader

  paginates_per 10

  belongs_to :album, counter_cache: :photos_counter

  def author_id
    album.user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, PhotoUploader

  has_many :albums

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  accepts_nested_attributes_for :albums, allow_destroy: true

  validates_presence_of :email
  validates_uniqueness_of :email, :username

  def display_name
    first_name.present? && last_name.present? ? "#{first_name} #{last_name}" : email
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @albums = current_user.albums.order('id DESC').page(params[:page] || 1)
  end

  def show
    @photos = @album.photos.order('id DESC').page(params[:page] || 1)
  end

  def new
    @album = current_user.albums.new
  end

  def edit; end

  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
    end
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:id, :name, photos_attributes: %i[id image description])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_album

  %w[
    ActiveRecord::RecordNotFound
    AbstractController::ActionNotFound
    ActionController::RoutingError
  ].each do |exception|
    rescue_from exception, with: :render_404
  end

  def render_404
    render 'application/404', status: 404
  end

  def current_album
    Album.find(params[:album_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController; end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController; end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController; end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def show; end

  protected

  def configure_sign_up_params
    keys = %i[first_name last_name username image]
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
  end

  def configure_account_update_params
    keys = %i[first_name last_name username image]
    devise_parameter_sanitizer.permit(:account_update, keys: keys)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController; end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController; end

app/views/albums/_album.html.slim
.col-xs-3
  .block-small
    = link_to album
      = image_tag (album.photos.first.image_url rescue 'default_image.png'), class: 'img img-responsive img-preview'
  .row
    .col-xs-10
      = album.name

app/views/albums/_form.html.slim
= form_for @album, html: { multipart: true }  do |f|
  - if @album.errors.any?
    #error_explanation
      h2 = "#{pluralize(@album.errors.count, 'error')} prohibited this album from being saved:"
      ul
        - @album.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  = f.fields_for :photos do |ff|
    = ff.file_field :image

    = ff.label :description
    = ff.text_field :description
  .actions = f.submit

app/views/albums/_photo.html.slim
#image-box-wrapper.image-box-wrapper
  .image-box
    .image-container
      = image_tag photo.image_url
    .image-details
      .details
        h4 Description:
        p = photo.description.empty? ? 'No decription provided' : photo.description
        = link_to 'Full Size Photo', photo.image_url, target: '_blank', class: 'btn btn-default'
  .clear

app/views/albums/_photo_fields.html.slim
.nested-fields
  .field
    = f.label :description
    br
    = f.text_field :description
  .field
    = f.file_field :image
  = link_to_remove_association 'remove photo', f

app/views/albums/edit.html.slim
h1 Editing album
= form_for @album do |f|
  h3 photos
  #tasks
    = f.fields_for :photos do |photo|
      = render 'photo_fields', f: photo
    .links
      = link_to_add_association 'add photo', f, :photos
  = f.submit

app/views/albums/index.html.slim
h1.text-center#label Listing albums
.row#albums
  - @albums.each do |album|
    == render 'album', album: album
  .col-xs-3
    .block-small
      = link_to new_album_path
        #box.new-album
          #overlay
            span#plus +
.row#paginator = paginate @albums, remote: true

app/views/albums/index.js.erb
$('#albums').html('<%= j render @albums %>');

$('#paginator').html('<%= j (paginate(@albums, :remote => true).to_s) %>');

app/views/albums/new.html.slim
h1 New album

== render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.slim
= link_to 'Edit', edit_album_path, class: 'btn btn-warning btn-xs'
h2.text-center.text-capitalize
  = best_in_place @album, :name
.row
  #photos
    - @photos.each do |photo|
      == render 'photo', photo: photo
  .image-box-wrapper
    .image-box
      .image-container
        = image_tag 'new_photo.png', style: 'background-color: white'
      .image-details
        .details
          = form_for(@album, html: {multipart: true}) do |f|
            = f.fields_for :photos, @album.photos.build do |ff|
              = ff.file_field :image, required: ''
            = f.submit
    .clear
.row#paginator = paginate @photos, remote: true

app/views/albums/show.js.erb
$('#photos')
  .html(`
    <% @photos.each do |photo| %>
      <%= render 'photo', photo: photo %>
    <% end %>
  `)

$('#paginator').html('<%= j (paginate(@photos, :remote => true).to_s) %>')

app/views/application/404.html.slim
section#error-page
  .row
    .col-sm-12
      .text-center
        = image_tag '404.png'
        h2 PAGE NOT FOUND
        p The page you are looking for might have been removed or had its name changed.
        = link_to 'RETURN TO THE HOMEPAGE', root_url, class: 'btn btn-error'

app/views/home/show.html.slim
/Header
header.img-box.text-center
  h1.title Main title

app/views/layouts/application.html.slim
doctype html
html
  head
    title Test Task
    = favicon_link_tag 'logo.png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body class="#{controller_name} #{action_name}"
    == render 'shared/navbar'
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? 'danger' : 'success' } alert-dismissable", role: 'alert' do
          button.close type='button' data-dismiss='alert'
            span aria-hidden='true' &times;
            span.sr-only Close
          = msg
      - unless controller_name == 'home'
        = link_to 'Back', :back, class: 'btn btn-info btn-xs' rescue redirect_to root_url
      = yield

app/views/photos/_form.html.slim
= form_for [current_album, @photo] do |f|
  - if @photo.errors.any?
    #error_explanation
      h2 = "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      ul
        - @photo.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :image
    = f.file_field :image
  .actions = f.submit

app/views/photos/edit.html.slim
h1 Editing photo

== render 'form'

= link_to 'Show', [current_album, @photo]
'  |
= link_to 'Back', album_photos_path(current_album)

app/views/photos/show.html.slim
p#notice = notice

p
  strong Image:
  = @photo.image_url

= link_to 'Edit', edit_album_photo_path([current_album, @photo])
'  |
= link_to 'Back', album_photos_path(current_album)

app/views/shared/_modal.html.slim
.modal-with-link.modal-dialog[role="document"]
  .modal-content
    .modal-header.text-center
      button.close[type="button" data-dismiss="modal" aria-label="Close"]
        span[aria-hidden="true"]
          | ×
      h4#gridSystemModalLabel.modal-title
        | Shortened link to this album
    .modal-body
      #shortened_url

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to root_url, class: 'navbar-brand'
        = image_tag 'logo_with_text.png', class: 'logo'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li = link_to 'Gallery', albums_path
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = image_tag current_user.image_url, class: 'img img-responsive profile-photo'
          li = link_to current_user.display_name , profile_url
          li = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          li = link_to 'Sign up', new_user_registration_url
          li = link_to 'Log in', user_session_url